/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/exercise7/quizScreen`; params?: Router.UnknownInputParams; } | { pathname: `/exercise7/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(information)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(information)'}/contact` | `/contact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6/BackgroundTheme`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6/CrudScreenContext`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6/hooksButtons`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6/ThemeToggle`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/effects`; params?: Router.UnknownInputParams; } | { pathname: `/hooks`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/state`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/Test1`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/exercise7/quizScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise7/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(information)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(information)'}/contact` | `/contact`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise6/BackgroundTheme`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise6/CrudScreenContext`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise6/hooksButtons`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise6`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise6/ThemeToggle`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/effects`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/state`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/Test1`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/exercise7/quizScreen${`?${string}` | `#${string}` | ''}` | `/exercise7/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(information)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `${'/(information)'}/contact${`?${string}` | `#${string}` | ''}` | `/contact${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exercises${`?${string}` | `#${string}` | ''}` | `/exercises${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/exercise6/BackgroundTheme${`?${string}` | `#${string}` | ''}` | `/exercise6/CrudScreenContext${`?${string}` | `#${string}` | ''}` | `/exercise6/hooksButtons${`?${string}` | `#${string}` | ''}` | `/exercise6${`?${string}` | `#${string}` | ''}` | `/exercise6/ThemeToggle${`?${string}` | `#${string}` | ''}` | `/hooks/effects${`?${string}` | `#${string}` | ''}` | `/hooks${`?${string}` | `#${string}` | ''}` | `/hooks/state${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/settings/Test1${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/exercise7/quizScreen`; params?: Router.UnknownInputParams; } | { pathname: `/exercise7/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(information)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(information)'}/contact` | `/contact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6/BackgroundTheme`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6/CrudScreenContext`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6/hooksButtons`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6`; params?: Router.UnknownInputParams; } | { pathname: `/exercise6/ThemeToggle`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/effects`; params?: Router.UnknownInputParams; } | { pathname: `/hooks`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/state`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/Test1`; params?: Router.UnknownInputParams; };
    }
  }
}
